# Generated by Django 6.1.1 on 2026-09-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContenuSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_site', models.CharField(default='AGRI-VICTOIRE', max_length=120)),
                ('slogan', models.CharField(default='Des produits agricoles frais, directement du producteur.', max_length=255)),
                ('texte_a_propos', models.TextField(default='AGRI-VICTOIRE est une plateforme de publication et de commande de produits agricoles.')),
                ('image_entete', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('whatsapp', models.URLField(blank=True)),
            ],
        ),
    ]
